Multiple Defenders Entirely in Defense Area
RoboCup-SSL/ssl-rules pull request #22
Opened 2020-02-02 20:35 UTC by rhololkeolke

Penalty is now a red card.

See https://docs.google.com/spreadsheets/d/1LfNNrE4ld0IkRGXSkKSKOnPDipdKbuH-InZJY2kATs4/edit?usp=sharing

2020-02-03 19:25 UTC, g3force requested changes

2020-02-03 19:25 UTC, g3force commented on chapters/offenses.adoc
> +Fouls are violations of the rules that result in a some combination of
```suggestion
Fouls are violations of the rules that result in some combination of
```

2020-02-03 19:25 UTC, g3force commented on chapters/offenses.adoc
> +inside its own defense area, the game is stopped and a <<Red Card, red
in #14 it was suggested/decided to keep the penalty kick (which is turned into a one-on-one kick) for the multiple defender foul.

2020-03-03 21:38 UTC, rhololkeolke commented
Closed in favor of #32

2020-03-03 21:38 UTC, closed without merging